# Generated by Django 2.0.5 on 2018-06-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fort', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '堡垒机用户', 'verbose_name_plural': '堡垒机用户'},
        ),
    ]
