# Generated by Django 2.0.5 on 2018-06-01 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fort', '0002_auto_20180601_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteuserbindhost',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fort.Host', verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='remoteuserbindhost',
            name='remote_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fort.RemoteUser', verbose_name='用户名'),
        ),
    ]
